# @summary Options to an include item of a fileset
# @author Tobias @towo Wolter <tobias.wolter+voxpupuli@b1-systems.de>
# @see https://docs.bareos.org/Configuration/Director.html#fileset-options
type Bareos::FilesetOptions = Struct[{
  Optional['Auto Exclude'] => Bareos::Boolean,
  Optional['Compression'] => Bareos::Compression,
  Optional['Signature'] => Bareos::Signature,
  Optional['Base Job'] => Bareos::VerifyOptions,
  Optional['Accurate'] => Bareos::VerifyOptions,
  Optional['Verify'] => Bareos::VerifyOptions,
  Optional['One FS'] => Bareos::Boolean,
  Optional['Honor No Dump Flag'] => Bareos::Boolean,
  Optional['Portable'] => Bareos::Boolean,
  Optional['Recurse'] => Bareos::Boolean,
  Optional['Sparse'] => Bareos::Boolean,
  Optional['Read Fifo'] => Bareos::Boolean,
  Optional['No Atime'] => Bareos::Boolean,
  Optional['Mtime Only'] => Bareos::Boolean,
  Optional['Keep Atime'] => Bareos::Boolean,
  Optional['Check File Changes'] => Bareos::Boolean,
  Optional['Hard Links'] => Bareos::Boolean,
  Optional['Wild'] => Bareos::List::String,
  Optional['Wild Dir'] => Bareos::List::String,
  Optional['Wild File'] => Bareos::List::String,
  Optional['Regex'] => Bareos::List::String,
  Optional['Regex File'] => Bareos::List::String,
  Optional['Regex Dir'] => Bareos::List::String,
  Optional['Exclude'] => Bareos::Boolean,
  Optional['ACL Support'] => Bareos::Boolean,
  Optional['XAttr Support'] => Bareos::Boolean,
  Optional['Ignore Case'] => Bareos::Boolean,
  Optional['FS Type'] => String,
  Optional['Drive Type'] => String,
  Optional['Hfs Plus Support'] => Bareos::Boolean,
  Optional['Strip Path'] => Integer,
  Optional['Size'] => String,
  Optional['Shadowing'] => Enum[
    'none',
    'localwarn',
    'localremove',
    'globalwarn',
    'globalremove'
  ],
  Optional['Meta'] => String,
}]
